#!/bin/bash
# make an exception class

class=$1
[[ -n $class ]] || {
   echo "usage: $0 classname"
   exit 1
}

case $class in 
  *Exception ) 
     ;;
  *)   class="${class}Exception";
     ;;
esac

echo "Generating $class"

cat > ${class}.java  << END
/* ========================================================================
 * Copyright (c) 2011 The University of Washington
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ========================================================================
 */

package edu.washington.iam.ws.cabroker.exception;

public class $class extends Exception {
  public $class() {
    super();
  }
  public $class(String msg) {
    super(msg);
  }
  public $class(String msg, Throwable cause) {
    super(msg, cause);
  }
  public $class(Throwable cause) {
    super(cause);
  }
}
END

